### ISSUE TITLE
MacOS: users[fields[2]]: bad array subscript

### ISSUE THREAD

**Issue by thomasmerz** [izabera/ps#3]
I tested this also on my MacOS with bash version 3.2.57(1)-release (from MacOS) and 5.2.26(1)-release (from HomeBrew). But both don't work:
> ./psaux.bash: line 32: users[fields[2]]: bad array subscript

Should it or do you want it to work also on MacOS or is this not intended?

**Comment by izabera** [comment]
mate go find something else to do

**Comment by izabera** [comment]
this script uses 238725 linux specific things.  it will never work on macos.  i doubt it even works on linux machines older than like a decade

**Comment by izabera** [comment]
line 32 is trying to parse /etc/passwd, which doesn't seem to exist on macos from what i've read (never used a mac so idk)

so it tried to subscript an array with an empty string, which is an invalid subscript
